// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// logh
double logh(double u, int m, DoubleVector y, DoubleVector eta, double lambda, double sigma);
RcppExport SEXP _il_sfa_logh(SEXP uSEXP, SEXP mSEXP, SEXP ySEXP, SEXP etaSEXP, SEXP lambdaSEXP, SEXP sigmaSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type lambda(lambdaSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    rcpp_result_gen = Rcpp::wrap(logh(u, m, y, eta, lambda, sigma));
    return rcpp_result_gen;
END_RCPP
}
// getEffectsHN
DoubleVector getEffectsHN(double lnlambda, double lnsigma, Rcpp::List list_eta, Rcpp::List list_y, int niter, DoubleVector uinit);
RcppExport SEXP _il_sfa_getEffectsHN(SEXP lnlambdaSEXP, SEXP lnsigmaSEXP, SEXP list_etaSEXP, SEXP list_ySEXP, SEXP niterSEXP, SEXP uinitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lnlambda(lnlambdaSEXP);
    Rcpp::traits::input_parameter< double >::type lnsigma(lnsigmaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type list_eta(list_etaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type list_y(list_ySEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type uinit(uinitSEXP);
    rcpp_result_gen = Rcpp::wrap(getEffectsHN(lnlambda, lnsigma, list_eta, list_y, niter, uinit));
    return rcpp_result_gen;
END_RCPP
}
// likHN
double likHN(double lnlambda, double lnsigma, Rcpp::List list_eta, Rcpp::List list_y, int niter, DoubleVector uinit, DoubleVector ws, DoubleVector z);
RcppExport SEXP _il_sfa_likHN(SEXP lnlambdaSEXP, SEXP lnsigmaSEXP, SEXP list_etaSEXP, SEXP list_ySEXP, SEXP niterSEXP, SEXP uinitSEXP, SEXP wsSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type lnlambda(lnlambdaSEXP);
    Rcpp::traits::input_parameter< double >::type lnsigma(lnsigmaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type list_eta(list_etaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type list_y(list_ySEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type uinit(uinitSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type ws(wsSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(likHN(lnlambda, lnsigma, list_eta, list_y, niter, uinit, ws, z));
    return rcpp_result_gen;
END_RCPP
}
// logf
double logf(double u, int m, DoubleVector y, DoubleVector eta, double sigmav, DoubleVector sigmau);
RcppExport SEXP _il_sfa_logf(SEXP uSEXP, SEXP mSEXP, SEXP ySEXP, SEXP etaSEXP, SEXP sigmavSEXP, SEXP sigmauSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type u(uSEXP);
    Rcpp::traits::input_parameter< int >::type m(mSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type y(ySEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type eta(etaSEXP);
    Rcpp::traits::input_parameter< double >::type sigmav(sigmavSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type sigmau(sigmauSEXP);
    rcpp_result_gen = Rcpp::wrap(logf(u, m, y, eta, sigmav, sigmau));
    return rcpp_result_gen;
END_RCPP
}
// likEHET
double likEHET(DoubleVector gamma, double lnsigmav, Rcpp::List list_eta, Rcpp::List list_y, Rcpp::List list_z, int niter, DoubleVector uinit, DoubleVector ws, DoubleVector z);
RcppExport SEXP _il_sfa_likEHET(SEXP gammaSEXP, SEXP lnsigmavSEXP, SEXP list_etaSEXP, SEXP list_ySEXP, SEXP list_zSEXP, SEXP niterSEXP, SEXP uinitSEXP, SEXP wsSEXP, SEXP zSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DoubleVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type lnsigmav(lnsigmavSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type list_eta(list_etaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type list_y(list_ySEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type list_z(list_zSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type uinit(uinitSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type ws(wsSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type z(zSEXP);
    rcpp_result_gen = Rcpp::wrap(likEHET(gamma, lnsigmav, list_eta, list_y, list_z, niter, uinit, ws, z));
    return rcpp_result_gen;
END_RCPP
}
// getEffectsEHET
DoubleVector getEffectsEHET(DoubleVector gamma, double lnsigmav, Rcpp::List list_eta, Rcpp::List list_y, Rcpp::List list_z, int niter, DoubleVector uinit);
RcppExport SEXP _il_sfa_getEffectsEHET(SEXP gammaSEXP, SEXP lnsigmavSEXP, SEXP list_etaSEXP, SEXP list_ySEXP, SEXP list_zSEXP, SEXP niterSEXP, SEXP uinitSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< DoubleVector >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< double >::type lnsigmav(lnsigmavSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type list_eta(list_etaSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type list_y(list_ySEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type list_z(list_zSEXP);
    Rcpp::traits::input_parameter< int >::type niter(niterSEXP);
    Rcpp::traits::input_parameter< DoubleVector >::type uinit(uinitSEXP);
    rcpp_result_gen = Rcpp::wrap(getEffectsEHET(gamma, lnsigmav, list_eta, list_y, list_z, niter, uinit));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_il_sfa_logh", (DL_FUNC) &_il_sfa_logh, 6},
    {"_il_sfa_getEffectsHN", (DL_FUNC) &_il_sfa_getEffectsHN, 6},
    {"_il_sfa_likHN", (DL_FUNC) &_il_sfa_likHN, 8},
    {"_il_sfa_logf", (DL_FUNC) &_il_sfa_logf, 6},
    {"_il_sfa_likEHET", (DL_FUNC) &_il_sfa_likEHET, 9},
    {"_il_sfa_getEffectsEHET", (DL_FUNC) &_il_sfa_getEffectsEHET, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_il_sfa(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
