# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

logh <- function(u, m, y, eta, lambda, sigma) {
    .Call(`_ilsfa_logh`, u, m, y, eta, lambda, sigma)
}

getEffectsHN <- function(lnlambda, lnsigma, list_eta, list_y, niter, uinit) {
    .Call(`_ilsfa_getEffectsHN`, lnlambda, lnsigma, list_eta, list_y, niter, uinit)
}

likHN <- function(lnlambda, lnsigma, list_eta, list_y, niter, uinit, ws, z) {
    .Call(`_ilsfa_likHN`, lnlambda, lnsigma, list_eta, list_y, niter, uinit, ws, z)
}

logf <- function(u, m, y, eta, sigmav, sigmau) {
    .Call(`_ilsfa_logf`, u, m, y, eta, sigmav, sigmau)
}

likEHET <- function(gamma, lnsigmav, list_eta, list_y, list_z, niter, uinit, ws, z) {
    .Call(`_ilsfa_likEHET`, gamma, lnsigmav, list_eta, list_y, list_z, niter, uinit, ws, z)
}

getEffectsEHET <- function(gamma, lnsigmav, list_eta, list_y, list_z, niter, uinit) {
    .Call(`_ilsfa_getEffectsEHET`, gamma, lnsigmav, list_eta, list_y, list_z, niter, uinit)
}

dnormgam <- function(y, mu, sigma, alpha, lambda) {
    .Call(`_ilsfa_dnormgam`, y, mu, sigma, alpha, lambda)
}

Ii12 <- function(y, mu, sigma, alpha, lambda) {
    .Call(`_ilsfa_Ii12`, y, mu, sigma, alpha, lambda)
}

Euy <- function(y, mu, sigma, alpha, lambda, logden) {
    .Call(`_ilsfa_Euy`, y, mu, sigma, alpha, lambda, logden)
}

logh_G <- function(u, m, y, eta, sigma, alpha, lambda) {
    .Call(`_ilsfa_logh_G`, u, m, y, eta, sigma, alpha, lambda)
}

Euyall <- function(sigma, alpha, lambda, list_eta, list_y, alphavec) {
    .Call(`_ilsfa_Euyall`, sigma, alpha, lambda, list_eta, list_y, alphavec)
}

logHess <- function(u, m, y, eta, sigma, alpha, lambda) {
    .Call(`_ilsfa_logHess`, u, m, y, eta, sigma, alpha, lambda)
}

getEffectsG <- function(lnsigma, lnalpha, lnlambda, list_eta, list_y, niter, uinit) {
    .Call(`_ilsfa_getEffectsG`, lnsigma, lnalpha, lnlambda, list_eta, list_y, niter, uinit)
}

minlogh <- function(u, m, y, eta, sigma, alpha, lambda) {
    .Call(`_ilsfa_minlogh`, u, m, y, eta, sigma, alpha, lambda)
}

getEffectsGS <- function(lnsigma, lnalpha, lnlambda, list_eta, list_y, ulow, uup, eps) {
    .Call(`_ilsfa_getEffectsGS`, lnsigma, lnalpha, lnlambda, list_eta, list_y, ulow, uup, eps)
}

likG <- function(lnsigma, lnalpha, lnlambda, list_eta, list_y, ulow, uup, eps, ws, z, niter, uinit, method) {
    .Call(`_ilsfa_likG`, lnsigma, lnalpha, lnlambda, list_eta, list_y, ulow, uup, eps, ws, z, niter, uinit, method)
}

